name: youtube_downloader
description: |
  Um aplicativo desenvolvido em Flutter para baixar vídeos e músicas do YouTube. Com o uso das bibliotecas youtube_explode_dart para interagir com a API do YouTube, dio para realizar requisições HTTP, path_provider para acessar o sistema de arquivos e file_picker para permitir ao usuário escolher o local de salvamento dos arquivos baixados.
#author: Danrlei Corrêa
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  youtube_explode_dart: ^2.0.0
  path_provider: ^2.1.3
  file_picker: ^8.0.0+1
  font_awesome_flutter: ^10.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_overlay_loader: ^2.0.0
  clipboard: ^0.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true  
  assets:
    - assets/ffmpeg/ffmpeg.exe

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"