name: youtube_downloader
description: |
  Um aplicativo desenvolvido em Flutter para baixar vídeos e músicas do YouTube. Com o uso das bibliotecas youtube_explode_dart para interagir com a API do YouTube, dio para realizar requisições HTTP, path_provider para acessar o sistema de arquivos e file_picker para permitir ao usuário escolher o local de salvamento dos arquivos baixados.
#author: Danrlei Corrêa
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 #  cupertino_icons: ^1.0.6
  path_provider: ^2.1.5
  file_picker: ^10.2.0
  font_awesome_flutter: ^10.7.0
  flutter_launcher_icons: ^0.14.4
  flutter_overlay_loader: ^2.0.0
  clipboard: ^2.0.2
  shared_preferences: ^2.5.3
  animations: ^2.0.11
  responsive_framework: ^1.5.1
  device_preview: ^1.3.1
  http: ^1.6.0
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true  

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"